theme: jekyll-theme-merlot
show_downloads: true


# Name of your site (displayed in the header)
#name: Ismael Núñez

# Short bio or description (displayed in the header)
#description: Developer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/12835964?s=200&u=24178961dde24ade6d3de189139a32a25480affb&v=4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: ismenc
  instagram: ismenc94
  linkedin: ismenc
  pinterest: ismenc
  rss:
  twitter:
  stackoverflow:
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: u/0/106915401369543945703
  
  plugins:
  - jemoji